---
# Source: webfrontend/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: RELEASE-NAME-webfrontend
  labels:
    helm.sh/chart: webfrontend-0.1.0
    app.kubernetes.io/name: webfrontend
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v1"
    app.kubernetes.io/managed-by: Helm
---
# Source: webfrontend/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-webfrontend
  labels:
    helm.sh/chart: webfrontend-0.1.0
    app.kubernetes.io/name: webfrontend
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: webfrontend
    app.kubernetes.io/instance: RELEASE-NAME
---
# Source: webfrontend/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-webfrontend
  labels:
    helm.sh/chart: webfrontend-0.1.0
    app.kubernetes.io/name: webfrontend
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webfrontend
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webfrontend
        app.kubernetes.io/instance: RELEASE-NAME
    spec:
      serviceAccountName: RELEASE-NAME-webfrontend
      securityContext:
        {}
      containers:
        - name: webfrontend
          securityContext:
            {}
          image: "kofigo253acr.azurecr.io/webfrontend:v1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
# Source: webfrontend/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "RELEASE-NAME-webfrontend-test-connection"
  labels:
    helm.sh/chart: webfrontend-0.1.0
    app.kubernetes.io/name: webfrontend
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['RELEASE-NAME-webfrontend:80']
  restartPolicy: Never
